# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bicycle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for Bicycle

  use_frameworks!
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  pod 'AwaitKit'
  pod 'JWTDecode'
  pod 'Reachability'
  pod 'Alamofire-SwiftyJSON'
  pod 'SwiftyJSON', '~> 4.0'
end
